---
- hosts: localhost
  become: yes
  become_method: sudo
  tasks:
    - name: add sublime pacman repository
      lineinfile: 
        path: /etc/pacman.conf
        line: "[sublime-text]\nServer = https://download.sublimetext.com/arch/dev/x86_64"
        state: present
    - name: update repository cache
      pacman:
        update_cache: yes
    - name: uninstall potentially preinstalled packages
      pacman:
        name: virtualbox-guest-utils-nox
        state: absent
    - name: install command line only packages
      pacman:
        name:
          - zsh
          - vim
          - htop
          - tree
          - screenfetch
          - rsync
          - git
          - openssh
          - unzip
          - zip
          - tmux
          - screen
          - trash-cli
          - jq
          - curl
          - wget
          - base-devel
          - ncdu
          # for funsies
          - nethack
          - figlet
        state: latest
    - name: install development tools
      pacman:
        name:
          - tk
          - jdk8-openjdk
          - docker
        state: latest
    - name: install base gui packages
      pacman:
        name:
          - xorg-xinit
          - xorg-server
          - libglvnd
          - virtualbox-guest-modules-arch
          - virtualbox-guest-utils
        state: latest
    - name: install desktop environment
      pacman:
        name:
          - chromium
          - compton
          - xclip
          - xdotool
          - terminator
          - rofi
          - dunst
          - ttf-ubuntu-font-family
          - noto-fonts
          - nitrogen
          - i3-gaps
          - i3blocks
          - gparted
        state: latest
    - name: install nice terminal stuff
      pacman:
        name:
          - powerline
          - powerline-fonts
    - name: install gui development tools
      pacman:
        name:
          - meld
          - gitg
          - dbeaver
          - sublime-text
        state: latest
