---
- hosts: localhost
  tasks:
    - name: set user shell
      become: yes
      become_method: sudo
      user:
        name: vagrant
        group: docker
        shell: /bin/zsh
        append: yes
    - name: clone dotfiles repo
      become: yes
      become_user: vagrant
      git: 
        repo: https://github.com/madstanners/dotfiles.git
        update: no
        dest: /home/vagrant/git/github.com/madstanners/dotfiles
    - name: dotfiles dir in env (.profile)
      become: yes
      become_user: vagrant
      lineinfile:
        create: yes
        path: /home/vagrant/.profile
        line: "export DOTFILES=/home/vagrant/git/github.com/madstanners/dotfiles"
        state: present
    - name: dotfiles dir in env (.zprofile)
      lineinfile:
        create: yes
        path: /home/vagrant/.zprofile
        line: "export DOTFILES=/home/vagrant/git/github.com/madstanners/dotfiles"
        state: present
    - name: dotfiles dir in env (.bash_profile)
      lineinfile:
        create: yes
        path: /home/vagrant/.bash_profile
        line: "export DOTFILES=/home/vagrant/git/github.com/madstanners/dotfiles"
        state: present
